/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kidmathgame;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.*;
import java.util.Random;
/**
 *
 * @author Ai
 */
public class GameFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainScreen = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        highScoreButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        prePlayButton = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        gameName = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        playScreen = new javax.swing.JPanel();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        answerField = new javax.swing.JTextField();
        plusIcon = new javax.swing.JLabel();
        lineIcon = new javax.swing.JLabel();
        scoreField = new javax.swing.JTextField();
        scoreLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        timeBar = new javax.swing.JProgressBar();
        homeButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        skipButton = new javax.swing.JButton();
        congratMessage = new javax.swing.JLabel();
        highScorePanel = new javax.swing.JPanel();
        score1 = new javax.swing.JTextField();
        score2 = new javax.swing.JTextField();
        score3 = new javax.swing.JTextField();
        score4 = new javax.swing.JTextField();
        score5 = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        name3 = new javax.swing.JTextField();
        name4 = new javax.swing.JTextField();
        name5 = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        homeButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adding game");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        mainScreen.setOpaque(false);
        mainScreen.setLayout(null);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/buttons/quit.png"))); // NOI18N
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        mainScreen.add(exitButton);
        exitButton.setBounds(120, 420, 166, 61);

        highScoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/buttons/highscore.png"))); // NOI18N
        highScoreButton.setBorderPainted(false);
        highScoreButton.setContentAreaFilled(false);
        highScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoreButtonActionPerformed(evt);
            }
        });
        mainScreen.add(highScoreButton);
        highScoreButton.setBounds(120, 340, 170, 60);

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/buttons/play.png"))); // NOI18N
        playButton.setBorder(null);
        playButton.setBorderPainted(false);
        playButton.setContentAreaFilled(false);
        playButton.setVisible(false);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        mainScreen.add(playButton);
        playButton.setBounds(120, 420, 166, 61);

        prePlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/buttons/play.png"))); // NOI18N
        prePlayButton.setBorder(null);
        prePlayButton.setBorderPainted(false);
        prePlayButton.setContentAreaFilled(false);
        prePlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prePlayButtonActionPerformed(evt);
            }
        });
        mainScreen.add(prePlayButton);
        prePlayButton.setBounds(120, 260, 166, 61);

        userName.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 50)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 51, 51));
        userName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userName.setVisible(false);
        mainScreen.add(userName);
        userName.setBounds(110, 320, 200, 80);

        gameName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/MathIcon.png"))); // NOI18N
        mainScreen.add(gameName);
        gameName.setBounds(100, 20, 205, 219);

        nameLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        nameLabel.setText("Enter Your Name");
        nameLabel.setVisible(false);
        mainScreen.add(nameLabel);
        nameLabel.setBounds(80, 240, 270, 70);

        getContentPane().add(mainScreen);
        mainScreen.setBounds(190, 0, 400, 500);

        playScreen.setOpaque(false);
        playScreen.setLayout(null);

        num1.setEditable(false);
        num1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 80)); // NOI18N
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        playScreen.add(num1);
        num1.setBounds(120, 10, 140, 120);

        num2.setEditable(false);
        num2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 80)); // NOI18N
        playScreen.add(num2);
        num2.setBounds(120, 170, 140, 130);

        answerField.setFont(new java.awt.Font("Tempus Sans ITC", 0, 80)); // NOI18N
        answerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerFieldActionPerformed(evt);
            }
        });
        answerField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                answerFieldKeyPressed(evt);
            }
        });
        playScreen.add(answerField);
        answerField.setBounds(120, 350, 140, 130);

        plusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/plus.png"))); // NOI18N
        playScreen.add(plusIcon);
        plusIcon.setBounds(10, 110, 96, 90);

        lineIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/line.png"))); // NOI18N
        playScreen.add(lineIcon);
        lineIcon.setBounds(0, 300, 350, 40);

        scoreField.setEditable(false);
        scoreField.setFont(new java.awt.Font("Tempus Sans ITC", 0, 80)); // NOI18N
        scoreField.setText("0");
        scoreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreFieldActionPerformed(evt);
            }
        });
        playScreen.add(scoreField);
        scoreField.setBounds(480, 90, 110, 70);

        scoreLabel.setFont(new java.awt.Font("Kristen ITC", 1, 30)); // NOI18N
        scoreLabel.setText("Score");
        playScreen.add(scoreLabel);
        scoreLabel.setBounds(480, 20, 100, 60);

        timeLabel.setFont(new java.awt.Font("Kristen ITC", 1, 30)); // NOI18N
        timeLabel.setText("Time");
        playScreen.add(timeLabel);
        timeLabel.setBounds(480, 180, 100, 60);

        timeBar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timeBar.setForeground(new java.awt.Color(51, 51, 255));
        timeBar.setMaximum(30);
        timeBar.setString(Integer.toString(timeBar.getValue()) + "s");
        timeBar.setStringPainted(true);
        playScreen.add(timeBar);
        timeBar.setBounds(380, 250, 330, 40);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/buttons/home.png"))); // NOI18N
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        playScreen.add(homeButton);
        homeButton.setBounds(610, 370, 110, 110);

        enterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/buttons/Enter.png"))); // NOI18N
        enterButton.setBorderPainted(false);
        enterButton.setContentAreaFilled(false);
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        playScreen.add(enterButton);
        enterButton.setBounds(340, 360, 120, 110);

        skipButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/buttons/skip.png"))); // NOI18N
        skipButton.setBorderPainted(false);
        skipButton.setContentAreaFilled(false);
        skipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipButtonActionPerformed(evt);
            }
        });
        playScreen.add(skipButton);
        skipButton.setBounds(480, 360, 120, 110);

        congratMessage.setFont(new java.awt.Font("Tempus Sans ITC", 1, 40)); // NOI18N
        congratMessage.setForeground(new java.awt.Color(255, 51, 51));
        congratMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/HighScores.png"))); // NOI18N
        congratMessage.setVisible(false);
        playScreen.add(congratMessage);
        congratMessage.setBounds(360, 200, 360, 120);

        getContentPane().add(playScreen);
        playScreen.setBounds(0, 0, 740, 500);
        playScreen.setVisible(false);

        highScorePanel.setVisible(false);
        highScorePanel.setOpaque(false);
        highScorePanel.setLayout(null);

        score1.setEditable(false);
        score1.setFont(new java.awt.Font("Tiger", 1, 30)); // NOI18N
        highScorePanel.add(score1);
        score1.setBounds(400, 140, 110, 40);

        score2.setEditable(false);
        score2.setFont(new java.awt.Font("Tiger", 1, 30)); // NOI18N
        highScorePanel.add(score2);
        score2.setBounds(400, 200, 110, 40);

        score3.setEditable(false);
        score3.setFont(new java.awt.Font("Tiger", 1, 30)); // NOI18N
        highScorePanel.add(score3);
        score3.setBounds(400, 260, 110, 40);

        score4.setEditable(false);
        score4.setFont(new java.awt.Font("Tiger", 1, 30)); // NOI18N
        highScorePanel.add(score4);
        score4.setBounds(400, 320, 110, 40);

        score5.setEditable(false);
        score5.setFont(new java.awt.Font("Tiger", 1, 30)); // NOI18N
        highScorePanel.add(score5);
        score5.setBounds(400, 380, 110, 40);

        name1.setEditable(false);
        name1.setFont(new java.awt.Font("Tiger", 1, 30)); // NOI18N
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        highScorePanel.add(name1);
        name1.setBounds(220, 140, 150, 40);

        name2.setEditable(false);
        name2.setFont(new java.awt.Font("Tiger", 1, 30)); // NOI18N
        highScorePanel.add(name2);
        name2.setBounds(220, 200, 150, 40);

        name3.setEditable(false);
        name3.setFont(new java.awt.Font("Tiger", 1, 30)); // NOI18N
        name3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name3ActionPerformed(evt);
            }
        });
        highScorePanel.add(name3);
        name3.setBounds(220, 260, 150, 40);

        name4.setEditable(false);
        name4.setFont(new java.awt.Font("Tiger", 1, 30)); // NOI18N
        name4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name4ActionPerformed(evt);
            }
        });
        highScorePanel.add(name4);
        name4.setBounds(220, 320, 150, 40);

        name5.setEditable(false);
        name5.setFont(new java.awt.Font("Tiger", 1, 30)); // NOI18N
        name5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name5ActionPerformed(evt);
            }
        });
        highScorePanel.add(name5);
        name5.setBounds(220, 380, 150, 40);

        label.setFont(new java.awt.Font("Tempus Sans ITC", 1, 80)); // NOI18N
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/TopScores.png"))); // NOI18N
        highScorePanel.add(label);
        label.setBounds(240, 40, 270, 80);

        homeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/buttons/home.png"))); // NOI18N
        homeButton1.setBorderPainted(false);
        homeButton1.setContentAreaFilled(false);
        homeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton1ActionPerformed(evt);
            }
        });
        highScorePanel.add(homeButton1);
        homeButton1.setBounds(610, 380, 110, 110);

        getContentPane().add(highScorePanel);
        highScorePanel.setBounds(0, 0, 760, 500);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kidmathgame/images/flash_cards.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 800, 500);

        getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(758, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        //Update high score list before exit
        //Cannot write file when run program as jar file.
        //ProcessingData.writeFile("highscore.txt");
        //ProcessingData.writeFile("name.txt");
        System.exit(0);
        
    }//GEN-LAST:event_exitButtonActionPerformed

    private void highScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoreButtonActionPerformed
        // TODO add your handling code here:
        mainScreen.setVisible(false);
        highScorePanel.setVisible(true);
        ProcessingData.displayHighScore();
    }//GEN-LAST:event_highScoreButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
        mainScreen.setVisible(false);
        playScreen.setVisible(true);
        answerField.setEditable(true);
        congratMessage.setVisible(false);
        timeBar.setVisible(true);
        timeLabel.setVisible(true);
        nameLabel.setVisible(false);
        userName.setVisible(false);
        enterButton.setVisible(true);
        skipButton.setVisible(true);
        ProcessingData.changeQuestion();
        ProcessingData.playSound("play.wav");
        //start counting timer
        ProcessingData.countTime();
    }//GEN-LAST:event_playButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        mainScreen.setVisible(true);
        playScreen.setVisible(false);
        highScoreButton.setVisible(true);
        exitButton.setVisible(true);
        prePlayButton.setVisible(true);
        playButton.setVisible(false);
        ProcessingData.timer.stop(); // stop timer
        ProcessingData.score = 0; // set score back to 0 when come back to main screen
        scoreField.setText("0");
        num2.setText(null);

    }//GEN-LAST:event_homeButtonActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed

    private void scoreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreFieldActionPerformed

    private void answerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerFieldActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void name3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name3ActionPerformed

    private void name4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name4ActionPerformed

    private void name5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name5ActionPerformed

    private void homeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton1ActionPerformed
        // TODO add your handling code here:
        mainScreen.setVisible(true);
        highScorePanel.setVisible(false);
    }//GEN-LAST:event_homeButton1ActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
        String answer = answerField.getText();
        int resultInt = Integer.parseInt(num1.getText())+ Integer.parseInt(num2.getText());
        String result = Integer.toString(resultInt);
        if(answer.equals(result))
        {
            ProcessingData.score++;
            //System.out.println(ProcessingData.score);
            scoreField.setText(Integer.toString(ProcessingData.score));
            ProcessingData.playSound("correct.au");
            //Change to new question
            ProcessingData.changeQuestion();
        }
        else
        {
            ProcessingData.playSound("wrong.au");
        }
            
    }//GEN-LAST:event_enterButtonActionPerformed

    private void skipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipButtonActionPerformed
        // TODO add your handling code here:
        //Change to new question
        ProcessingData.playSound("skip.au");
        ProcessingData.changeQuestion();
            
    }//GEN-LAST:event_skipButtonActionPerformed

    private void prePlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prePlayButtonActionPerformed
        // TODO add your handling code here:
        highScoreButton.setVisible(false);
        exitButton.setVisible(false);
        prePlayButton.setVisible(false);
        playButton.setVisible(true);
        userName.setVisible(true);
        nameLabel.setVisible(true);
    }//GEN-LAST:event_prePlayButtonActionPerformed

    private void answerFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_answerFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String answer = answerField.getText();
        int resultInt = Integer.parseInt(num1.getText())+ Integer.parseInt(num2.getText());
        String result = Integer.toString(resultInt);
        if(answer.equals(result))
        {
            ProcessingData.score++;
            //System.out.println(ProcessingData.score);
            scoreField.setText(Integer.toString(ProcessingData.score));
            ProcessingData.playSound("correct.au");
            //Change to new question
            ProcessingData.changeQuestion();
        }
        else
        {
            ProcessingData.playSound("wrong.au");
        }
        }
    }//GEN-LAST:event_answerFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true); 
                ProcessingData.createScoreList();
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField answerField;
    private javax.swing.JLabel background;
    public static javax.swing.JLabel congratMessage;
    public static javax.swing.JButton enterButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel gameName;
    private javax.swing.JButton highScoreButton;
    private javax.swing.JPanel highScorePanel;
    public static javax.swing.JButton homeButton;
    private javax.swing.JButton homeButton1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lineIcon;
    private javax.swing.JPanel mainScreen;
    public static javax.swing.JTextField name1;
    public static javax.swing.JTextField name2;
    public static javax.swing.JTextField name3;
    public static javax.swing.JTextField name4;
    public static javax.swing.JTextField name5;
    private javax.swing.JLabel nameLabel;
    public static javax.swing.JTextField num1;
    public static javax.swing.JTextField num2;
    private javax.swing.JButton playButton;
    private javax.swing.JPanel playScreen;
    private javax.swing.JLabel plusIcon;
    private javax.swing.JButton prePlayButton;
    public static javax.swing.JTextField score1;
    public static javax.swing.JTextField score2;
    public static javax.swing.JTextField score3;
    public static javax.swing.JTextField score4;
    public static javax.swing.JTextField score5;
    public static javax.swing.JTextField scoreField;
    private javax.swing.JLabel scoreLabel;
    public static javax.swing.JButton skipButton;
    public static javax.swing.JProgressBar timeBar;
    public static javax.swing.JLabel timeLabel;
    public static javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
